# Import Libs and Get Dataset

In [0]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [88]:
df = pd.read_csv('train.csv')
df.head()

top_left_square top_middle_square  ... class Id
0               x                 x  ...     0  0
1               x                 x  ...     0  1
2               x                 x  ...     0  3
3               x                 x  ...     0  7
4               x                 x  ...     0  8

[5 rows x 11 columns]

In [89]:
x_train = df.iloc[:, 0:9]
y_train = df['class']
x_train.head()

top_left_square top_middle_square  ... bottom_middle_square bottom_right_square
0               x                 x  ...                    o                   o
1               x                 x  ...                    x                   o
2               x                 x  ...                    b                   b
3               x                 x  ...                    b                   o
4               x                 x  ...                    o                   o

[5 rows x 9 columns]

In [90]:
x_test = pd.read_csv('test.csv')
x_test.head()

top_left_square top_middle_square  ... bottom_right_square Id
0               x                 x  ...                   x  2
1               x                 x  ...                   b  4
2               x                 x  ...                   o  5
3               x                 x  ...                   b  6
4               x                 x  ...                   b  9

[5 rows x 10 columns]

In [0]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

x_train['top_left_square'] = encoder.fit_transform(x_train['top_left_square'])
x_train['top_middle_square'] = encoder.fit_transform(x_train['top_middle_square'])
x_train['top_right_square'] = encoder.fit_transform(x_train['top_right_square'])
x_train['middle_left_square'] = encoder.fit_transform(x_train['middle_left_square'])
x_train['middle_middle_square'] = encoder.fit_transform(x_train['middle_middle_square'])
x_train['middle_right_square'] = encoder.fit_transform(x_train['middle_right_square'])
x_train['bottom_left_square'] = encoder.fit_transform(x_train['bottom_left_square'])
x_train['bottom_middle_square'] = encoder.fit_transform(x_train['bottom_middle_square'])
x_train['bottom_right_square'] = encoder.fit_transform(x_train['bottom_right_square'])

x_test['top_left_square'] = encoder.fit_transform(x_test['top_left_square'])
x_test['top_middle_square'] = encoder.fit_transform(x_test['top_middle_square'])
x_test['top_right_square'] = encoder.fit_transform(x_test['top_right_square'])
x_test['middle_left_square'] = encoder.fit_transform(x_test['middle_left_square'])
x_test['middle_middle_square'] = encoder.fit_transform(x_test['middle_middle_square'])
x_test['middle_right_square'] = encoder.fit_transform(x_test['middle_right_square'])
x_test['bottom_left_square'] = encoder.fit_transform(x_test['bottom_left_square'])
x_test['bottom_middle_square'] = encoder.fit_transform(x_test['bottom_middle_square'])
x_test['bottom_right_square'] = encoder.fit_transform(x_test['bottom_right_square'])

In [92]:
x_train.head()

top_left_square  ...  bottom_right_square
0                2  ...                    1
1                2  ...                    1
2                2  ...                    0
3                2  ...                    1
4                2  ...                    1

[5 rows x 9 columns]

In [101]:
clf.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [102]:
x_test_pred = x_test.iloc[:, 0:9]
x_test_pred.head()

top_left_square  ...  bottom_right_square
0                2  ...                    2
1                2  ...                    0
2                2  ...                    1
3                2  ...                    0
4                2  ...                    0

[5 rows x 9 columns]

In [0]:
y_pred = clf.predict(x_test_pred)

In [138]:
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [139]:
y_pred.shape

(296,)

In [140]:
y_test_id = x_test['Id']
y_test_id.shape

(296,)

In [147]:
combined = np.vstack((y_test_id, y_pred)).T
combined.shape

(296, 2)

In [0]:
np.savetxt('datathon19.csv', combined, delimiter=',', fmt="%i")

In [160]:
asdf =  pd.read_csv('datathon19.csv')
asdf.head()

2  1
0   4  0
1   5  0
2   6  0
3   9  0
4  10  0

In [0]:
import csv
with open('datathon19.csv',newline='') as f:
    r = csv.reader(f)
    data = [line for line in r]
with open('datathon19.csv','w',newline='') as f:
    w = csv.writer(f)
    w.writerow(['Id','class'])
    w.writerows(data)

# Calculating Accuracy Using Oirignal Dataset

In [0]:
dfOrigin = pd.read_csv('tic_tac_toe_dataset.csv')

In [114]:
x = dfOrigin.iloc[:, 0:9]
y = dfOrigin['class']
x.head()

top_left_square top_middle_square  ... bottom_middle_square bottom_right_square
0               x                 x  ...                    o                   o
1               x                 x  ...                    x                   o
2               x                 x  ...                    o                   x
3               x                 x  ...                    b                   b
4               x                 x  ...                    o                   b

[5 rows x 9 columns]

In [0]:
from sklearn.model_selection import train_test_split

x_train_origin, x_test_origin, y_train_origin, y_test_origin = train_test_split(x, y, random_state = 47, test_size = 0.25)

In [116]:
x_train_origin.head()
y_train_origin.head()

713    negative
294    positive
91     positive
899    negative
160    positive
Name: class, dtype: object

In [0]:
clf2 = DecisionTreeClassifier(criterion = 'entropy')

In [118]:
x_train_origin['top_left_square'] = encoder.fit_transform(x_train_origin['top_left_square'])
x_train_origin['top_middle_square'] = encoder.fit_transform(x_train_origin['top_middle_square'])
x_train_origin['top_right_square'] = encoder.fit_transform(x_train_origin['top_right_square'])
x_train_origin['middle_left_square'] = encoder.fit_transform(x_train_origin['middle_left_square'])
x_train_origin['middle_middle_square'] = encoder.fit_transform(x_train_origin['middle_middle_square'])
x_train_origin['middle_right_square'] = encoder.fit_transform(x_train_origin['middle_right_square'])
x_train_origin['bottom_left_square'] = encoder.fit_transform(x_train_origin['bottom_left_square'])
x_train_origin['bottom_middle_square'] = encoder.fit_transform(x_train_origin['bottom_middle_square'])
x_train_origin['bottom_right_square'] = encoder.fit_transform(x_train_origin['bottom_right_square'])

x_test_origin['top_left_square'] = encoder.fit_transform(x_test_origin['top_left_square'])
x_test_origin['top_middle_square'] = encoder.fit_transform(x_test_origin['top_middle_square'])
x_test_origin['top_right_square'] = encoder.fit_transform(x_test_origin['top_right_square'])
x_test_origin['middle_left_square'] = encoder.fit_transform(x_test_origin['middle_left_square'])
x_test_origin['middle_middle_square'] = encoder.fit_transform(x_test_origin['middle_middle_square'])
x_test_origin['middle_right_square'] = encoder.fit_transform(x_test_origin['middle_right_square'])
x_test_origin['bottom_left_square'] = encoder.fit_transform(x_test_origin['bottom_left_square'])
x_test_origin['bottom_middle_square'] = encoder.fit_transform(x_test_origin['bottom_middle_square'])
x_test_origin['bottom_right_square'] = encoder.fit_transform(x_test_origin['bottom_right_square'])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documenta

In [119]:
x_test_origin.head()

top_left_square  ...  bottom_right_square
490                0  ...                    2
737                2  ...                    2
298                1  ...                    1
787                1  ...                    1
666                2  ...                    0

[5 rows x 9 columns]

In [120]:
x_test_origin.head()

top_left_square  ...  bottom_right_square
490                0  ...                    2
737                2  ...                    2
298                1  ...                    1
787                1  ...                    1
666                2  ...                    0

[5 rows x 9 columns]

In [121]:
y_train_origin.head()

713    negative
294    positive
91     positive
899    negative
160    positive
Name: class, dtype: object

In [0]:
y_train_origin =  encoder.fit_transform(y_train_origin)
y_test_origin =  encoder.fit_transform(y_test_origin)

In [123]:
y_test_origin[0:5]

array([1, 0, 1, 0, 0])

In [124]:
clf2.fit(x_train_origin, y_train_origin)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [0]:
y_pred_origin = clf.predict(x_test_origin)

In [126]:
y_pred_origin

array([0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1])

In [127]:
from sklearn.metrics import accuracy_score
print('Accuracy Score on train data: ', accuracy_score(y_true=y_train_origin, y_pred=clf.predict(x_train_origin)))
print('Accuracy Score on test data: ', accuracy_score(y_true=y_test_origin, y_pred=y_pred_origin))

Accuracy Score on train data:  0.04735376044568245
Accuracy Score on test data:  0.029166666666666667
