# Import Libs and Get Dataset

In [0]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('train.csv')
df.head()

top_left_square top_middle_square  ... class Id
0               x                 x  ...     0  0
1               x                 x  ...     0  1
2               x                 x  ...     0  3
3               x                 x  ...     0  7
4               x                 x  ...     0  8

[5 rows x 11 columns]

# Preprocessing: Using Label Encoder

In [3]:
x_train = df.iloc[:, 0:9]
y_train = df['class']
x_train.head()

top_left_square top_middle_square  ... bottom_middle_square bottom_right_square
0               x                 x  ...                    o                   o
1               x                 x  ...                    x                   o
2               x                 x  ...                    b                   b
3               x                 x  ...                    b                   o
4               x                 x  ...                    o                   o

[5 rows x 9 columns]

In [4]:
x_test = pd.read_csv('test.csv')
x_test.head()

top_left_square top_middle_square  ... bottom_right_square Id
0               x                 x  ...                   x  2
1               x                 x  ...                   b  4
2               x                 x  ...                   o  5
3               x                 x  ...                   b  6
4               x                 x  ...                   b  9

[5 rows x 10 columns]

In [0]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

x_train['top_left_square'] = encoder.fit_transform(x_train['top_left_square'])
x_train['top_middle_square'] = encoder.fit_transform(x_train['top_middle_square'])
x_train['top_right_square'] = encoder.fit_transform(x_train['top_right_square'])
x_train['middle_left_square'] = encoder.fit_transform(x_train['middle_left_square'])
x_train['middle_middle_square'] = encoder.fit_transform(x_train['middle_middle_square'])
x_train['middle_right_square'] = encoder.fit_transform(x_train['middle_right_square'])
x_train['bottom_left_square'] = encoder.fit_transform(x_train['bottom_left_square'])
x_train['bottom_middle_square'] = encoder.fit_transform(x_train['bottom_middle_square'])
x_train['bottom_right_square'] = encoder.fit_transform(x_train['bottom_right_square'])

x_test['top_left_square'] = encoder.fit_transform(x_test['top_left_square'])
x_test['top_middle_square'] = encoder.fit_transform(x_test['top_middle_square'])
x_test['top_right_square'] = encoder.fit_transform(x_test['top_right_square'])
x_test['middle_left_square'] = encoder.fit_transform(x_test['middle_left_square'])
x_test['middle_middle_square'] = encoder.fit_transform(x_test['middle_middle_square'])
x_test['middle_right_square'] = encoder.fit_transform(x_test['middle_right_square'])
x_test['bottom_left_square'] = encoder.fit_transform(x_test['bottom_left_square'])
x_test['bottom_middle_square'] = encoder.fit_transform(x_test['bottom_middle_square'])
x_test['bottom_right_square'] = encoder.fit_transform(x_test['bottom_right_square'])

In [6]:
x_train.head()

top_left_square  ...  bottom_right_square
0                2  ...                    1
1                2  ...                    1
2                2  ...                    0
3                2  ...                    1
4                2  ...                    1

[5 rows x 9 columns]

# Building the Model

Previously I had used DecisionTreeClassifier which gave just about 89% accuracy in the below test I did with the Original dataset. Now trying RandomForestClassifier with n_estimators=20000

In [60]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=20000)
model.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [61]:
x_test_pred = x_test.iloc[:, 0:9]
x_test_pred.head()

top_left_square  ...  bottom_right_square
0                2  ...                    2
1                2  ...                    0
2                2  ...                    1
3                2  ...                    0
4                2  ...                    0

[5 rows x 9 columns]

# Make predictions using the trained model

In [0]:
y_pred = model.predict(x_test_pred)

In [63]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0])

In [64]:
y_pred.shape

(296,)

In [65]:
y_test_id = x_test['Id']
y_test_id.shape

(296,)

In [66]:
combined = np.vstack((y_test_id, y_pred)).T
combined.shape

(296, 2)

In [0]:
np.savetxt('datathon19.csv', combined, delimiter=',', fmt="%i")

In [68]:
asdf =  pd.read_csv('datathon19.csv')
asdf.head()

2  0
0   4  0
1   5  0
2   6  0
3   9  0
4  10  0

In [0]:
import csv
with open('datathon19.csv',newline='') as f:
    r = csv.reader(f)
    data = [line for line in r]
with open('datathon19.csv','w',newline='') as f:
    w = csv.writer(f)
    w.writerow(['Id','class'])
    w.writerows(data)

# Calculating Accuracy Using Oirignal Dataset

This is just to show the accuracy score of the trained model. Previously done with DecisionTreeClassifier which yielded about 89% accuracy.

In [0]:
dfOrigin = pd.read_csv('tic_tac_toe_dataset.csv')

In [71]:
x = dfOrigin.iloc[:, 0:9]
y = dfOrigin['class']
x.head()

top_left_square top_middle_square  ... bottom_middle_square bottom_right_square
0               x                 x  ...                    o                   o
1               x                 x  ...                    x                   o
2               x                 x  ...                    o                   x
3               x                 x  ...                    b                   b
4               x                 x  ...                    o                   b

[5 rows x 9 columns]


# Preprocessing: Using LabelEncoder

In [0]:
from sklearn.model_selection import train_test_split

x_train_origin, x_test_origin, y_train_origin, y_test_origin = train_test_split(x, y, random_state = 47, test_size = 0.25)

In [73]:
x_train_origin.head()
y_train_origin.head()

713    negative
294    positive
91     positive
899    negative
160    positive
Name: class, dtype: object

In [0]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=20000)
# model.fit(x_train_origin, y_train_origin)

In [0]:
x_train_origin['top_left_square'] = encoder.fit_transform(x_train_origin['top_left_square'])
x_train_origin['top_middle_square'] = encoder.fit_transform(x_train_origin['top_middle_square'])
x_train_origin['top_right_square'] = encoder.fit_transform(x_train_origin['top_right_square'])
x_train_origin['middle_left_square'] = encoder.fit_transform(x_train_origin['middle_left_square'])
x_train_origin['middle_middle_square'] = encoder.fit_transform(x_train_origin['middle_middle_square'])
x_train_origin['middle_right_square'] = encoder.fit_transform(x_train_origin['middle_right_square'])
x_train_origin['bottom_left_square'] = encoder.fit_transform(x_train_origin['bottom_left_square'])
x_train_origin['bottom_middle_square'] = encoder.fit_transform(x_train_origin['bottom_middle_square'])
x_train_origin['bottom_right_square'] = encoder.fit_transform(x_train_origin['bottom_right_square'])

x_test_origin['top_left_square'] = encoder.fit_transform(x_test_origin['top_left_square'])
x_test_origin['top_middle_square'] = encoder.fit_transform(x_test_origin['top_middle_square'])
x_test_origin['top_right_square'] = encoder.fit_transform(x_test_origin['top_right_square'])
x_test_origin['middle_left_square'] = encoder.fit_transform(x_test_origin['middle_left_square'])
x_test_origin['middle_middle_square'] = encoder.fit_transform(x_test_origin['middle_middle_square'])
x_test_origin['middle_right_square'] = encoder.fit_transform(x_test_origin['middle_right_square'])
x_test_origin['bottom_left_square'] = encoder.fit_transform(x_test_origin['bottom_left_square'])
x_test_origin['bottom_middle_square'] = encoder.fit_transform(x_test_origin['bottom_middle_square'])
x_test_origin['bottom_right_square'] = encoder.fit_transform(x_test_origin['bottom_right_square'])

In [76]:
x_test_origin.head()

top_left_square  ...  bottom_right_square
490                0  ...                    2
737                2  ...                    2
298                1  ...                    1
787                1  ...                    1
666                2  ...                    0

[5 rows x 9 columns]

In [77]:
x_test_origin.head()

top_left_square  ...  bottom_right_square
490                0  ...                    2
737                2  ...                    2
298                1  ...                    1
787                1  ...                    1
666                2  ...                    0

[5 rows x 9 columns]

In [0]:
y_train_origin =  encoder.fit_transform(y_train_origin)
y_test_origin =  encoder.fit_transform(y_test_origin)

In [79]:
y_test_origin[0:5]

array([1, 0, 1, 0, 0])

# Training the Model and making predictions

In [80]:
model.fit(x_train_origin, y_train_origin)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [0]:
y_pred_origin = model.predict(x_test_origin)

In [82]:
y_pred_origin

array([1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1])

# Accuracy score

Previously achieved 89% using DecisionTreeClassifier. Now, after using RandomForestClassifier there is a significant improvement, as the accuracy has gone up to almost 93%. Pretty decent.

In [83]:
from sklearn.metrics import accuracy_score
print('Accuracy Score on train data: ', accuracy_score(y_true=y_train_origin, y_pred=model.predict(x_train_origin)))
print('Accuracy Score on test data: ', accuracy_score(y_true=y_test_origin, y_pred=y_pred_origin))

Accuracy Score on train data:  1.0
Accuracy Score on test data:  0.925
