## Predict the Class Performance

Problem Statement
You are supposed to predict the performance of the student. 
The student are measured on different attribute standard 
and their performance are marked in the class column as Low, high and medium.
Do the necessary preprcessing and develop a model using an MLP classifier.

Hint: Preprocessing is mandate for the model to work. 

# Get the Dataset and Preprocess

In [0]:
import numpy as np
import pandas as pd

In [0]:
from sklearn.neural_network import MLPClassifier

In [0]:
df = pd.read_csv('Dataset-ISA2.csv')

In [4]:
df.head()

gender NationalITy  ... StudentAbsenceDays Class
0      M          KW  ...            Under-7     M
1      M          KW  ...            Under-7     M
2      M          KW  ...            Above-7     L
3      M          KW  ...            Above-7     L
4      M          KW  ...            Above-7     M

[5 rows x 17 columns]

In [0]:
y = df['Class']
x = df.iloc[:, 0:16]
# x.head()
# y.head()

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [0]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)
# x_train

In [0]:
x_train['gender'] = encoder.fit_transform(x_train['gender'])
x_train['NationalITy'] =  encoder.fit_transform(x_train['NationalITy'])
x_train['PlaceofBirth'] =  encoder.fit_transform(x_train['PlaceofBirth'])
x_train['StageID'] =  encoder.fit_transform(x_train['StageID'])
x_train['GradeID'] =  encoder.fit_transform(x_train['GradeID'])
x_train['SectionID'] =  encoder.fit_transform(x_train['SectionID'])
x_train['Topic'] =  encoder.fit_transform(x_train['Topic'])
x_train['Semester'] =  encoder.fit_transform(x_train['Semester'])
x_train['Relation'] =  encoder.fit_transform(x_train['Relation'])
x_train['ParentAnsweringSurvey'] =  encoder.fit_transform(x_train['ParentAnsweringSurvey'])
x_train['ParentschoolSatisfaction'] =  encoder.fit_transform(x_train['ParentschoolSatisfaction'])
x_train['StudentAbsenceDays'] =  encoder.fit_transform(x_train['StudentAbsenceDays'])

In [49]:
x_train.head()
# x_test.head

gender  NationalITy  ...  ParentschoolSatisfaction  StudentAbsenceDays
18        0            4  ...                         1                   1
99        1            4  ...                         0                   0
211       1            4  ...                         0                   1
115       1            4  ...                         1                   0
205       0            8  ...                         0                   0

[5 rows x 16 columns]

In [0]:
x_test['gender'] = encoder.fit_transform(x_test['gender'])
x_test['NationalITy'] =  encoder.fit_transform(x_test['NationalITy'])
x_test['PlaceofBirth'] =  encoder.fit_transform(x_test['PlaceofBirth'])
x_test['StageID'] =  encoder.fit_transform(x_test['StageID'])
x_test['GradeID'] =  encoder.fit_transform(x_test['GradeID'])
x_test['SectionID'] =  encoder.fit_transform(x_test['SectionID'])
x_test['Topic'] =  encoder.fit_transform(x_test['Topic'])
x_test['Semester'] =  encoder.fit_transform(x_test['Semester'])
x_test['Relation'] =  encoder.fit_transform(x_test['Relation'])
x_test['ParentAnsweringSurvey'] =  encoder.fit_transform(x_test['ParentAnsweringSurvey'])
x_test['ParentschoolSatisfaction'] =  encoder.fit_transform(x_test['ParentschoolSatisfaction'])
x_test['StudentAbsenceDays'] =  encoder.fit_transform(x_test['StudentAbsenceDays'])

In [51]:
x_test.head()

gender  NationalITy  ...  ParentschoolSatisfaction  StudentAbsenceDays
217       0            3  ...                         1                   1
16        1            4  ...                         0                   0
470       1            6  ...                         1                   1
116       0            4  ...                         1                   0
411       0            3  ...                         1                   1

[5 rows x 16 columns]

In [0]:
y = encoder.fit_transform(y)

In [59]:
y[0:5]

array([2, 2, 1, 1, 2])

# Building the Model

In [65]:
nn = MLPClassifier()
nn.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

# Prediction and Accuracy Score

In [0]:
pred = nn.predict(x_test)

In [69]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
acc = accuracy_score(y_test, pred)
acc

0.75

In [70]:
print(confusion_matrix(y_test, pred))

[[23  0  8]
 [ 0 18  5]
 [ 7  4 31]]


In [71]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           H       0.77      0.74      0.75        31
           L       0.82      0.78      0.80        23
           M       0.70      0.74      0.72        42

    accuracy                           0.75        96
   macro avg       0.76      0.75      0.76        96
weighted avg       0.75      0.75      0.75        96



# Grid Search

In [73]:
nn.get_params()

{'activation': 'relu',
 'alpha': 0.0001,
 'batch_size': 'auto',
 'beta_1': 0.9,
 'beta_2': 0.999,
 'early_stopping': False,
 'epsilon': 1e-08,
 'hidden_layer_sizes': (100,),
 'learning_rate': 'constant',
 'learning_rate_init': 0.001,
 'max_iter': 200,
 'momentum': 0.9,
 'n_iter_no_change': 10,
 'nesterovs_momentum': True,
 'power_t': 0.5,
 'random_state': None,
 'shuffle': True,
 'solver': 'adam',
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': False,
 'warm_start': False}

In [0]:
from sklearn.model_selection import GridSearchCV

In [0]:
grid = {
    'alpha': [0.1, 1, 0.01, 0.001],
    'activation': ['relu', 'tanh'],
    'hidden_layer_sizes': ((15, 12), (15,15)),
    'max_iter': [200, 100, 150]
}

In [0]:
grid_nn = GridSearchCV(nn, param_grid = grid)

In [80]:
grid_nn.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=MLPClassifier(activation='relu', alpha=0.0001,
                                     batch_size='auto', beta_1=0.9,
                                     beta_2=0.999, early_stopping=False,
                                     epsilon=1e-08, hidden_layer_sizes=(100,),
                                     learning_rate='constant',
                                     learning_rate_init=0.001, max_iter=200,
                                     momentum=0.9, n_iter_no_change=10,
                                     nesterovs_momentum=True, power_t=0.5,
                                     random_state=None, shuffle=True,
                                     solver='adam', tol=0.0001,
                                     validation_fraction=0.1, verbose=False,
                                     warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'activation': ['relu', 'tanh'],
    

In [0]:
pred1 = grid_nn.predict(x_test)

In [82]:
accuracy_score(y_test, pred)

0.75

In [83]:
grid_nn.best_params_

{'activation': 'relu',
 'alpha': 1,
 'hidden_layer_sizes': (15, 12),
 'max_iter': 200}