## Support Vector Machine Classification

Import the Redwine Dataset. You are supposed to estimate the redwine quality as the outcome variable.
Do Standard scaling on the train dataset and learn the model using SVM classifier. 
Perform a Grid Serach and find the best parameters of C and Gamma.
Visualize the classification boundary
Evaluate the model using the suitable performance metrics

# Import and Preprocessing

In [8]:
import pandas as pd
import numpy as np
df = pd.read_csv('Redwine.csv', delimiter = ';')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [9]:
df[:10]

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   
5            7.4              0.66         0.00             1.8      0.075   
6            7.9              0.60         0.06             1.6      0.069   
7            7.3              0.65         0.00             1.2      0.065   
8            7.8              0.58         0.02             2.0      0.073   
9            7.5              0.50         0.36             6.1      0.071   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   
5                 13.0                  40.0   0.9978  3.51       0.56   
6                 15.0                  59.0   0.9964  3.30       0.46   
7                 15.0                  21.0   0.9946  3.39       0.47   
8                  9.0                  18.0   0.9968  3.36       0.57   
9                 17.0                 102.0   0.9978  3.35       0.80   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5  
5      9.4        5  
6      9.4        5  
7     10.0        7  
8      9.5        7  
9     10.5        5

In [22]:
df.keys()

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [23]:
x = df[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol']]

In [27]:
y = df['quality']
y[:5]

0    5
1    5
2    5
3    6
4    5
Name: quality, dtype: int64

# Split into train and test and StandardScaler

In [48]:
from sklearn.model_selection import train_test_split

xTrain, xTest, yTrain, yTest =  train_test_split(x, y, test_size = 0.3, random_state=33) 

In [56]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(xTrain)
standardized_X = scaler.transform(xTrain)
standardized_X_test = scaler.transform(xTest)

# Build SVC

In [57]:
from sklearn.svm import SVC
model = SVC()

In [58]:
model.fit(standardized_X, yTrain)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

# Evaluation and Accuracy Score

In [60]:
predictions = model.predict(standardized_X_test)
predictions

array([5, 6, 5, 6, 5, 5, 5, 6, 6, 5, 5, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 7,
       5, 6, 5, 5, 6, 6, 5, 5, 6, 5, 5, 6, 6, 7, 6, 5, 6, 5, 5, 5, 5, 6,
       6, 6, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5, 5, 6, 7, 6,
       6, 6, 6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 5, 6, 6, 5, 6, 7, 6, 5, 5, 6,
       5, 5, 6, 5, 6, 6, 6, 6, 5, 5, 7, 6, 6, 6, 6, 6, 5, 5, 6, 7, 6, 6,
       5, 6, 5, 6, 6, 5, 5, 6, 6, 6, 6, 5, 5, 5, 6, 5, 5, 5, 5, 7, 6, 7,
       6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 5, 5, 6, 6, 6, 5, 6, 5, 5, 6, 6, 5,
       5, 6, 7, 6, 7, 6, 5, 5, 6, 5, 6, 6, 5, 5, 5, 6, 5, 6, 6, 6, 5, 5,
       6, 6, 5, 6, 5, 5, 7, 6, 6, 5, 6, 5, 5, 5, 6, 5, 5, 6, 5, 5, 5, 5,
       5, 5, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5, 6, 5, 5, 5, 7, 6, 6, 6, 5, 6,
       6, 6, 6, 6, 7, 5, 5, 7, 6, 5, 6, 6, 5, 6, 5, 5, 5, 6, 7, 5, 6, 5,
       5, 5, 6, 5, 6, 6, 5, 6, 5, 6, 5, 5, 5, 5, 7, 5, 6, 5, 5, 6, 6, 5,
       6, 5, 6, 6, 5, 7, 6, 6, 5, 5, 6, 5, 5, 5, 6, 6, 6, 6, 6, 5, 6, 6,
       6, 6, 5, 5, 6, 6, 6, 5, 6, 5, 5, 6, 5, 6, 6,

In [61]:
from sklearn.metrics import accuracy_score
accuracy_score(yTest, predictions)

0.6083333333333333

In [63]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(yTest, predictions))

[[  0   0   1   1   0   0]
 [  0   0   8   7   0   0]
 [  0   0 155  49   0   0]
 [  0   0  54 121   8   0]
 [  0   0   3  50  16   0]
 [  0   0   0   6   1   0]]


In [65]:
print(classification_report(yTest, predictions))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        15
           5       0.70      0.76      0.73       204
           6       0.52      0.66      0.58       183
           7       0.64      0.23      0.34        69
           8       0.00      0.00      0.00         7

    accuracy                           0.61       480
   macro avg       0.31      0.28      0.28       480
weighted avg       0.59      0.61      0.58       480



/home/harshaky/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# GridSearch

In [66]:
param_grid = {'C': [0.1, 1, 10, 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 'kernel': ['rbf']}

In [70]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3, cv = 9)

In [71]:
grid.fit(xTrain, yTrain)

Fitting 9 folds for each of 25 candidates, totalling 225 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.417, total=   0.1s
[CV] C=0.1, gamma=1, kernel=rbf ......................................


/home/harshaky/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 8 members, which is too few. The minimum number of members in any class cannot be less than n_splits=9.
  % (min_groups, self.n_splits)), Warning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s


[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.417, total=   0.1s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.424, total=   0.1s
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.2s remaining:    0.0s


[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.424, total=   0.1s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.427, total=   0.1s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.431, total=   0.1s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.431, total=   0.1s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.431, total=   0.1s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.434, total=   0.1s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.425, total=   0.1s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] .

[Parallel(n_jobs=1)]: Done 225 out of 225 | elapsed:   24.0s finished


GridSearchCV(cv=9, error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [72]:
grid.best_params_

{'C': 1000, 'gamma': 0.0001, 'kernel': 'rbf'}

In [73]:
grid.best_estimator_

SVC(C=1000, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [75]:
grid_predictions = grid.predict(xTest)

In [76]:
print(confusion_matrix(yTest, grid_predictions))

[[  0   0   1   1   0   0]
 [  0   0   9   6   0   0]
 [  0   0 152  51   1   0]
 [  0   0  72 111   0   0]
 [  0   0   5  63   1   0]
 [  0   0   0   7   0   0]]


In [77]:
print(classification_report(yTest, grid_predictions))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        15
           5       0.64      0.75      0.69       204
           6       0.46      0.61      0.53       183
           7       0.50      0.01      0.03        69
           8       0.00      0.00      0.00         7

    accuracy                           0.55       480
   macro avg       0.27      0.23      0.21       480
weighted avg       0.52      0.55      0.50       480



/home/harshaky/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
